steps:
  - name: Check wp-cli.
    plugin: Script
    script:
      - wp --info --allow-root
  - name: Update wp-cli.
    plugin: Script
    script:
      - wp cli update --allow-root --yes
  - name: Verify wp-cli version update.
    plugin: Script
    script:
      - wp --info --allow-root
